server {
    listen 80;
    server_name mymusic.laravel;

    location / {
        proxy_pass http://php-upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~/\.ht {
        deny all;
    }

}
